name: Verify the Baseline using Vagrant

on:
  push:
    branches: [ master, Sb-update ]
  pull_request:
    branches: [ master, Sb-update ]
  release:
    types:
      - published

jobs:
  my-job:
    name: Validate my profile
    runs-on: macos-latest
    env:
      CHEF_LICENSE: accept-silent
      KITCHEN_YAML: kitchen.vagrant.yml
    strategy:
      matrix:
        suite: ['vanilla', 'hardened']
      fail-fast: false
    steps:
      - name: Add jq for output formatting
        run: brew install jq
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Disable ri and rdoc
        run: 'echo "gem: --no-ri --no-rdoc" >> ~/.gemrc'
      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Regenerate current `profile.json`
        run: |
          bundle exec inspec json . | jq . > profile.json
      # - name: Run InSpec Vendor on Profile
      #   run: bundle exec inspec vendor --overwrite .
      - name: Lint the Inspec profile
        run: bundle exec inspec check .
      - name: Run kitchen test - Couchbase Coummunity 6.0.0
        run: bundle exec kitchen test --destroy=always ${{ matrix.suite }}-rhel-7-couchbase-600-community || true
      - name: Check Kitchen log
        run: cat .kitchen/logs/kitchen.log
      - name: Display our ${{ matrix.suite }} results summary - Couchbase Coummunity 6.0.0
        run: bundle exec inspec_tools summary -j spec/results/rhel-7-couchbase-6.0.0-community-${{ matrix.suite }}-test-result.json --json-counts | jq .
      - name: Ensure the scan meets our ${{ matrix.suite }} results threshold - Couchbase Coummunity 6.0.0
        run: bundle exec inspec_tools compliance -j spec/results/rhel-7-couchbase-6.0.0-community-${{ matrix.suite }}-test-result.json -f threshold.${{ matrix.suite }}.yml
      - name: Run kitchen test - Couchbase Coummunity 6.6.0
        run: bundle exec kitchen test --destroy=always ${{ matrix.suite }}-rhel-7-couchbase-660-community || true
      - name: Check Kitchen log
        run: cat .kitchen/logs/kitchen.log
      - name: Display our ${{ matrix.suite }} results summary - Couchbase Coummunity 6.6.0
        run: bundle exec inspec_tools summary -j spec/results/rhel-7-couchbase-6.6.0-community-${{ matrix.suite }}-test-result.json --json-counts | jq .
      - name: Ensure the scan meets our ${{ matrix.suite }} results threshold - Couchbase Coummunity 6.6.0
        run: bundle exec inspec_tools compliance -j spec/results/rhel-7-couchbase-6.6.0-community-${{ matrix.suite }}-test-result.json -f threshold.${{ matrix.suite }}.yml  
      - name: Save Test Result JSON
        uses: actions/upload-artifact@v2
        with:
          path: spec/results
